### ISSUE TITLE
Proper MSPI Sequence

### ISSUE THREAD

**Issue by Reggiedel** [estrepo/hrycg#12]
Mobile Care Service Center

**Luzon**
Greenbelt 3
SM Megamall
Power Plant Mall
SM Mall of Asia

Ayala Malls Vertis North
North East Square
The Podium
SM City Marikina
Glorietta 5
S Maison 
Festival Mall
SM City Clark
New Point Mall - soon to open this 2024
LIMA Estate - soon to open this 2024

**Visayas**
Robinsons Naga
Festive Walk
Robinsons Galleria Cebu

**Mindanao**
Limketkai Mall
Abreeza Mall
KCC Mall

**Comment by Reggiedel** [comment]
Facade Photo (Vertis North)



![Image](https://github.com/user-attachments/assets/e4773d10-3d74-484c-8e5c-37fe8c9b3974)


-APP MOA
-APP Megamall
https://drive.google.com/drive/folders/1ywKvDY1XFUomV6ERM0nU0p6pgAK8HYQo?usp=share_link

PPM https://drive.google.com/file/d/15ERObU39YEin-I5SsvkPYQT_fbJKgIXF/view?usp=sharing
Greenbelt https://drive.google.com/file/d/19Vmqq7B9x-X3rNW73rbodNr-o8Tx-lFm/view?usp=sharing

**Comment by chicodelacruz** [comment]
@Reggiedel @JohnArvinDugang 

I've already pushed this to production. Please have a look.

Thanks!

**Comment by Reggiedel** [comment]
Hello!

Please be advised that the sequence returned to its old sequence.

![Image](https://github.com/user-attachments/assets/7efb8823-78f1-4648-9dad-7ee6bc8b47bc)

**Comment by chicodelacruz** [comment]
Hi @JohnArvinDugang ,

Please investigate this issue. It looks like something is missing here. Try running both the main and mastdev branches on your local machine to see the difference.

Thanks,
Chico

**Comment by Reggiedel** [comment]
Hi Sir @JohnArvinDugang 

Please take note of correct names:

North East Square
S Maison

Thank you.
